export const MainMenuRoutes = [
  { label: 'Posting', route: '/awareness', id: 'awareness' },
  { label: 'Multiview', route: '/multiview', id: 'multiview' },
  { label: 'TV Clipper', route: '/liveClipping', id: 'liveClipping' },
  { label: 'Online Video Clipper', route: '/onlineVideos', id: 'onlineVideos' },
  { label: 'Print Clipper', route: '/print', id: 'print' },
  { label: 'Web Clipper', route: '/web', id: 'web' },
  { label: 'Social Clipper', route: '/social', id: 'twitter' },
  { label: 'Impact', route: '/impact', id: 'impact' },
  { label: 'Jobs', route: '/jobs', id: 'jobs' },
  { label: 'Hyper QC', route: '/hyper-qc', id: 'hyperQc' },
  { label: 'Search', route: '/search', id: 'search' },
  { label: 'Reports', route: '/reports', id: 'reports' },
  { label: 'Dashboard', route: '/dashboard', id: 'dashboard' },
  { label: 'Settings', route: '/settings/user', id: 'settings' },
  { label: 'Info', route: '/info', id: 'info' },
  { label: 'Work Assessment', route: '/work-assessment', id: 'work-assessment' },
  // { label: 'Search', route: '/clientSearch', id: 'clientSearch' },
  { label: 'Library', route: '/libraries', id: 'client-libraries' },
  { label: 'Media Manager', route: '/mediamanager', id: 'client-editor' },
  { label: 'Multiview', route: '/clientMultiview', id: 'client-multiview' },
  { label: 'Dashboard', route: '/clientDashboard', id: 'client-dashboard' },
  { label: 'Report', route: '/clientReports', id: 'client-reports' },
  { label: 'News Board', route: '/news-board', id: 'news-board' },
  { label: 'Map', route: '/map', id: 'map' },
];
